-- ============================================================================
-- 0001_initial_schema.up.sql
-- Flashback AI: Legacy Mode  -  initial canonical graph schema
-- ----------------------------------------------------------------------------
-- Creates:
--   * Node tables: persons, moments, entities, threads, traits, questions
--   * Generic edges table
--   * History table: moment_history
--   * Active views (active_moments, active_entities, ...)
--   * HNSW vector indexes on every embedded row
--   * updated_at triggers on every audited table
--
-- Conventions:
--   * UUID primary keys (gen_random_uuid())
--   * TIMESTAMPTZ for all timestamps
--   * status TEXT column for soft-delete / supersession / merge
--   * embedding completeness check: vector and (model, version) move together
--   * No FKs on `edges` (heterogeneous targets) - validated in app code
--
-- See SCHEMA.md for the full reference.
-- ============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

-- ----------------------------------------------------------------------------
-- Helpers
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- persons  -  the subject of a legacy
-- ============================================================================

CREATE TABLE persons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Identity
    name TEXT NOT NULL,
    relationship TEXT,                            -- contributor's relationship label
    profile_summary TEXT,                         -- generated by Profile Summary Generator

    -- Cold-start machinery
    phase TEXT NOT NULL DEFAULT 'starter'
        CHECK (phase IN ('starter', 'steady')),
    coverage_state JSONB NOT NULL DEFAULT
        '{"sensory":0,"voice":0,"place":0,"relation":0,"era":0}'::jsonb,
    phase_locked_at TIMESTAMPTZ,
    moments_at_last_thread_run INT NOT NULL DEFAULT 0,

    -- Stylized artifact (image, written by Node consumer of the artifact queue)
    image_url TEXT,
    thumbnail_url TEXT,
    generation_prompt TEXT,                       -- written by agent, consumed by Node

    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_persons_updated_at BEFORE UPDATE ON persons
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ============================================================================
-- moments  -  discrete recalled episodes
-- ============================================================================

CREATE TABLE moments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID NOT NULL REFERENCES persons(id) ON DELETE CASCADE,

    -- Content
    title TEXT NOT NULL,
    narrative TEXT NOT NULL,
    time_anchor JSONB,                            -- { year?, decade?, life_period?, era? }
    life_period_estimate TEXT,                    -- e.g. "childhood", "early career"
    sensory_details TEXT,
    emotional_tone TEXT,
    contributor_perspective TEXT,

    -- Status / supersession
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'superseded')),
    superseded_by UUID REFERENCES moments(id),

    -- Embedding
    narrative_embedding vector(1024),
    embedding_model TEXT,
    embedding_model_version TEXT,

    -- Stylized artifact (video for moments, with thumbnail)
    video_url TEXT,
    thumbnail_url TEXT,
    generation_prompt TEXT,

    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Embedding completeness: vector and (model, version) must move together
    CONSTRAINT chk_moments_embedding_complete CHECK (
        (narrative_embedding IS NULL
            AND embedding_model IS NULL
            AND embedding_model_version IS NULL)
        OR
        (narrative_embedding IS NOT NULL
            AND embedding_model IS NOT NULL
            AND embedding_model_version IS NOT NULL)
    )
);

CREATE INDEX moments_person_id_status_idx
    ON moments (person_id, status);
CREATE INDEX moments_person_recent_idx
    ON moments (person_id, created_at DESC)
    WHERE status = 'active';
CREATE INDEX moments_narrative_embedding_idx
    ON moments USING hnsw (narrative_embedding vector_cosine_ops)
    WHERE status = 'active';

CREATE TRIGGER trg_moments_updated_at BEFORE UPDATE ON moments
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ============================================================================
-- entities  -  people / places / objects / organizations mentioned in moments
-- ============================================================================

CREATE TABLE entities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID NOT NULL REFERENCES persons(id) ON DELETE CASCADE,

    -- Type and identity
    kind TEXT NOT NULL
        CHECK (kind IN ('person', 'place', 'object', 'organization')),
    name TEXT NOT NULL,
    description TEXT,
    aliases TEXT[] NOT NULL DEFAULT '{}',
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- attributes shape varies by kind; see SCHEMA.md

    -- Status / merge
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'merged')),
    merged_into UUID REFERENCES entities(id),

    -- Embedding
    description_embedding vector(1024),
    embedding_model TEXT,
    embedding_model_version TEXT,

    -- Stylized artifact (image)
    image_url TEXT,
    thumbnail_url TEXT,
    generation_prompt TEXT,

    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_entities_embedding_complete CHECK (
        (description_embedding IS NULL
            AND embedding_model IS NULL
            AND embedding_model_version IS NULL)
        OR
        (description_embedding IS NOT NULL
            AND embedding_model IS NOT NULL
            AND embedding_model_version IS NOT NULL)
    )
);

CREATE INDEX entities_person_id_status_idx
    ON entities (person_id, status);
CREATE INDEX entities_person_kind_status_idx
    ON entities (person_id, kind, status);
CREATE INDEX entities_aliases_gin
    ON entities USING gin (aliases);
CREATE INDEX entities_description_embedding_idx
    ON entities USING hnsw (description_embedding vector_cosine_ops)
    WHERE status = 'active';

CREATE TRIGGER trg_entities_updated_at BEFORE UPDATE ON entities
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ============================================================================
-- threads  -  emergent narrative arcs across moments
-- ============================================================================

CREATE TABLE threads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID NOT NULL REFERENCES persons(id) ON DELETE CASCADE,

    name TEXT NOT NULL,
    description TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'auto-detected'
        CHECK (source IN ('auto-detected', 'manual')),
    confidence REAL,

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived')),

    description_embedding vector(1024),
    embedding_model TEXT,
    embedding_model_version TEXT,

    image_url TEXT,
    thumbnail_url TEXT,
    generation_prompt TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_threads_embedding_complete CHECK (
        (description_embedding IS NULL
            AND embedding_model IS NULL
            AND embedding_model_version IS NULL)
        OR
        (description_embedding IS NOT NULL
            AND embedding_model IS NOT NULL
            AND embedding_model_version IS NOT NULL)
    )
);

CREATE INDEX threads_person_id_status_idx
    ON threads (person_id, status);
CREATE INDEX threads_description_embedding_idx
    ON threads USING hnsw (description_embedding vector_cosine_ops)
    WHERE status = 'active';

CREATE TRIGGER trg_threads_updated_at BEFORE UPDATE ON threads
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ============================================================================
-- traits  -  character properties of the subject
-- ============================================================================

CREATE TABLE traits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID NOT NULL REFERENCES persons(id) ON DELETE CASCADE,

    name TEXT NOT NULL,
    description TEXT,
    strength TEXT NOT NULL DEFAULT 'mentioned_once'
        CHECK (strength IN ('mentioned_once', 'moderate', 'strong', 'defining')),

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived')),

    description_embedding vector(1024),
    embedding_model TEXT,
    embedding_model_version TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_traits_embedding_complete CHECK (
        (description_embedding IS NULL
            AND embedding_model IS NULL
            AND embedding_model_version IS NULL)
        OR
        (description_embedding IS NOT NULL
            AND embedding_model IS NOT NULL
            AND embedding_model_version IS NOT NULL)
    )
);

CREATE INDEX traits_person_id_status_idx
    ON traits (person_id, status);
CREATE INDEX traits_description_embedding_idx
    ON traits USING hnsw (description_embedding vector_cosine_ops)
    WHERE status = 'active';

CREATE TRIGGER trg_traits_updated_at BEFORE UPDATE ON traits
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ============================================================================
-- questions  -  first-class question nodes
-- ============================================================================
-- person_id is NULLABLE: starter_anchor questions are GLOBAL TEMPLATES
-- shared across all legacies. Everything else is per-person.
-- ============================================================================

CREATE TABLE questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID REFERENCES persons(id) ON DELETE CASCADE,

    text TEXT NOT NULL,
    source TEXT NOT NULL
        CHECK (source IN (
            'starter_anchor',
            'dropped_reference',
            'underdeveloped_entity',
            'life_period_gap',
            'thread_deepen',
            'universal_dimension'
        )),
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Expected jsonb shape by source:
    --   starter_anchor:        { dimension: <one of 5>, themes: [..] }
    --   dropped_reference:     { dropped_phrase, themes }
    --   underdeveloped_entity: { themes }
    --   life_period_gap:       { life_period, themes }
    --   thread_deepen:         { themes }
    --   universal_dimension:   { dimension, themes }

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'asked', 'archived')),

    embedding vector(1024),
    embedding_model TEXT,
    embedding_model_version TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_questions_embedding_complete CHECK (
        (embedding IS NULL
            AND embedding_model IS NULL
            AND embedding_model_version IS NULL)
        OR
        (embedding IS NOT NULL
            AND embedding_model IS NOT NULL
            AND embedding_model_version IS NOT NULL)
    ),

    -- starter_anchor questions are global templates;
    -- everything else is per-person
    CONSTRAINT chk_questions_person_scope CHECK (
        (source = 'starter_anchor' AND person_id IS NULL)
        OR
        (source <> 'starter_anchor' AND person_id IS NOT NULL)
    )
);

CREATE INDEX questions_person_id_status_idx
    ON questions (person_id, status);
CREATE INDEX questions_source_status_idx
    ON questions (source, status);
-- Fast lookup of starter templates by dimension
CREATE INDEX questions_starter_dimension_idx
    ON questions ((attributes->>'dimension'))
    WHERE source = 'starter_anchor' AND status = 'active';
CREATE INDEX questions_embedding_idx
    ON questions USING hnsw (embedding vector_cosine_ops)
    WHERE status = 'active';

CREATE TRIGGER trg_questions_updated_at BEFORE UPDATE ON questions
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ============================================================================
-- edges  -  generic relationship table (the heart of the hybrid model)
-- ============================================================================
-- from_id / to_id are NOT FKs because they target different tables based on
-- from_kind / to_kind. App-level validate_edge() enforces allowed
-- combinations. See src/db/edges.py.
-- ============================================================================

CREATE TABLE edges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    from_kind TEXT NOT NULL
        CHECK (from_kind IN ('moment', 'entity', 'thread', 'trait', 'question', 'person')),
    from_id UUID NOT NULL,

    to_kind TEXT NOT NULL
        CHECK (to_kind IN ('moment', 'entity', 'thread', 'trait', 'question', 'person')),
    to_id UUID NOT NULL,

    edge_type TEXT NOT NULL
        CHECK (edge_type IN (
            'involves',
            'happened_at',
            'exemplifies',
            'evidences',
            'related_to',
            'motivated_by',
            'targets',
            'answered_by'
        )),

    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Prevent exact duplicate edges (same nodes + same type)
    UNIQUE (from_kind, from_id, to_kind, to_id, edge_type)
);

CREATE INDEX edges_from_idx
    ON edges (from_kind, from_id, edge_type, status);
CREATE INDEX edges_to_idx
    ON edges (to_kind, to_id, edge_type, status);
CREATE INDEX edges_type_status_idx
    ON edges (edge_type, status);

CREATE TRIGGER trg_edges_updated_at BEFORE UPDATE ON edges
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ============================================================================
-- moment_history  -  audit trail for user manual edits to moments
-- ============================================================================

CREATE TABLE moment_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    moment_id UUID NOT NULL REFERENCES moments(id) ON DELETE CASCADE,

    -- Snapshot of the field values BEFORE the edit
    previous_values JSONB NOT NULL,

    edited_by UUID NOT NULL,                      -- contributor user id (Node-side)
    edited_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX moment_history_moment_id_idx
    ON moment_history (moment_id, edited_at DESC);

-- ============================================================================
-- Active views
-- ----------------------------------------------------------------------------
-- All read-side code SHOULD query these views by default rather than the
-- base tables. This enforces invariant #1 (always filter status='active').
-- ============================================================================

CREATE VIEW active_persons    AS SELECT * FROM persons;
-- ^ persons has no status column today; included for API symmetry.
CREATE VIEW active_moments    AS SELECT * FROM moments    WHERE status = 'active';
CREATE VIEW active_entities   AS SELECT * FROM entities   WHERE status = 'active';
CREATE VIEW active_threads    AS SELECT * FROM threads    WHERE status = 'active';
CREATE VIEW active_traits     AS SELECT * FROM traits     WHERE status = 'active';
CREATE VIEW active_questions  AS SELECT * FROM questions  WHERE status = 'active';
CREATE VIEW active_edges      AS SELECT * FROM edges      WHERE status = 'active';

COMMIT;
